### ISSUE TITLE
Enchant Min/Max and Treasure Enchants

### ISSUE THREAD

**Issue by Shadowclaimer** [TheIllusiveC4/Champions#20] opened 2019-03-25 01:47 UTC
For Config-based enchants it'd be nice if we could choose Min/Max levels and Treasure Enchants instead of just using the Enchant_Randomly loot table function.

In the same vein, a durability min/max would be nice too.

**Comment by TheIllusiveC4** [comment] 2019-03-25 04:00
I'm a little ambivalent about this, but I think I'm going to have to reject this. I never liked having the config-based loot option in the first place, but I could see the merit in having a basic structure for loot so people who just want basic drops could add those in without having to dive into loot table editing. If I start making this more advanced, it starts becoming a substandard duplicate of the loot table system that's already in place and that's something I want to avoid.

**Closed by TheIllusiveC4** 2019-03-25 04:00 UTC
Labels: enhancement

**Comment by Shadowclaimer** [comment] 2019-03-25 04:04
That's fair and understandable. I'm trying to avoid delving into Loottweaker/Zenscript any more than I already have so figured it was worth asking. 

Thank you for your time.
