### ISSUE TITLE
GUI disappearing & weird champion mobs

### ISSUE THREAD

**Issue by JuJuicylene** [TheIllusiveC4/Champions#104] opened 2022-01-20 01:21 UTC
(i've already talked about this in the mod's comment section but i've figured that opening an issue would be better)

mod version: 1.16.5-2.0.1.8
forge version: 36.2.22
Notes: the following only happens when playing on presence of other mods.
> for the gui it is possibly due to having other gui elements added from mods (like elenai dodge, origins, and dungeons gear, which i play with the three).
> but for the glitched champions it might be related to dungeons gear and how some mobs display new behavior/ have been changed and etc...

First problem - GUI hiding away:
idk if this is intentional but when i look at a champion, the game's bars disappear (health, food, menu buttons and also the chat for some reason)

pics:
![image](https://user-images.githubusercontent.com/97467242/150244469-3ab88b85-d4bb-4853-a9d6-14a6a588da35.png)
this pic i had the game paused
![image](https://user-images.githubusercontent.com/97467242/150244954-4462bcd3-3f96-480c-9d30-f87779f13c86.png)

Second problem - Champion mobs "spawning incorrectly"
Sometimes champions spawn weirdly, without the particles and health bar, but instead they spawn like this:

pics:
![image](https://user-images.githubusercontent.com/97467242/150242789-d49d019a-b4be-4f68-a8e4-ddc346f61db7.png)
![image](https://user-images.githubusercontent.com/97467242/150244381-0c50e367-7c2b-4a4e-8c01-9825d7c28f45.png)

**Comment by TheIllusiveC4** [comment] 2022-01-20 06:27
Please fill out the bug report template properly. At the very least I need the Champions version, Forge version, and for you to verify if this issue occurs with _only_ Champions installed.

**Comment by JuJuicylene** [comment] 2022-01-22 02:57
> Please fill out the bug report template properly. At the very least I need the Champions version, Forge version, and for you to verify if this issue occurs with _only_ Champions installed.

 done 👍

**Comment by TheIllusiveC4** [comment] 2022-01-22 03:46
For the first problem, try and figure out which mod is causing the conflict. Obvious candidates would be any HUD mods or mods that change the GUI in some major way.

For the second problem, I don't think that's related to Champions. None of the terms or effects used would be caused by anything in the Champions code. If you take Champions out, do these special mobs still spawn?

**Comment by JuJuicylene** [comment] 2022-01-22 17:05
i can't pin point the exact mod that is causing the conflict for the first problem because there are many that seem to add new elements to the gui and hud, but none of them seem to add something really major, so the best i can do is list the mods im using that add stuff to it:
Origins, Too many origins, Ever potion (best candidate?), elenai dodge 2, dungeons gear.
> all of the listed above add something either to the hud or gui, new bars and stuff.


Now for the other problem, no it only happens when the champions mod is installed. Tho i've noticed that some of them are spawning with enchantments rather than affixes (like fire trail), so maybe its a direct conflict with dungeons gear, since it adds a lot of new enchantments and some of them can be seen on the mobs.

**Comment by TheIllusiveC4** [comment] 2022-03-02 03:55
I'm closing this in order to merge all related issues into: https://github.com/TheIllusiveC4/Champions/issues/108

At first glance it might not seem like the same issue, but I believe it is caused by the same underlying error.

**Closed as completed by TheIllusiveC4** 2022-03-02 03:55 UTC
Labels: bug, duplicate
