### ISSUE TITLE
1.15.2 crash

### ISSUE THREAD

**Issue by BedrockLegends** [TheIllusiveC4/Champions#50] opened 2020-06-16 14:59 UTC
#### Versions (Be specific, do not write "latest"):
* Champions: champions-FORGE-1.15.2-2.0-beta3.jar
* Forge: 31.2.20

#### Observed Behavior:
Single player locked up after doing /reload and then crashed to desktop
#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

https://gist.github.com/BedrockLegends/1cd62cf5915d537e4c9229fddf220f85

**Comment by TheIllusiveC4** [comment] 2020-06-16 18:10
Just need to make sure first, did you change the champion configs at all before you reloaded?

**Comment by TheIllusiveC4** [comment] 2020-06-16 18:50
I cannot reproduce this behavior. Doing `/reload` doesn't cause a crash, even when I summon a Champion mob. It seems like this is occurring because your ranks are empty. Did you edit the `champions-ranks.toml` file at all?

**Comment by BedrockLegends** [comment] 2020-06-16 23:29
No I did not, I left it default

**Comment by TheIllusiveC4** [comment] 2020-06-17 00:28
Very strange. Can you show me your `champions-ranks.toml` file? Also, does this happen every single time you do `/reload`?

**Comment by TheIllusiveC4** [comment] 2020-07-22 06:10
Closing this issue as it seems to be the same problem as this one and you're the same author: https://github.com/TheIllusiveC4/Champions/issues/54

**Closed as completed by TheIllusiveC4** 2020-07-22 06:10 UTC
Labels: bug, duplicate, cannot reproduce
