### ISSUE TITLE
[1.12.2] Champions from mob spawners when that's disabled

### ISSUE THREAD

**Issue by vizthex123** [TheIllusiveC4/Champions#55] opened 2020-07-23 22:42 UTC
#### Versions (Be specific, do not write "latest"):
* Champions: 1.0.11.9
* Forge: 14.23.5.2854

The option to prevent them from spawning from mob spawners is set to "false" (the default), but they're still coming from mob spawners when they aren't supposed to.

I've noticed this mainly in Roguelike Dungeons' buildings (as spawners are semi-rare otherwise), but it's really annoying.

Does the config option just work the opposite way I thought it did? The way it's phrased sounds like setting it to "true" allows champions to spawn from spawners

**Comment by TheIllusiveC4** [comment] 2020-07-23 23:18
Have you tested this with vanilla spawners at all? If not, then this is likely a duplicate of https://github.com/TheIllusiveC4/Champions/issues/46
You understand the config correctly. However, unless this is proven to be a problem with vanilla spawners as well, then this would need to be addressed by Roguelike Dungeons and their spawning method.

**Closed as completed by TheIllusiveC4** 2020-07-23 23:18 UTC
Labels: duplicate

**Comment by vizthex123** [comment] 2020-07-26 01:01
Vanilla spawners are the only ones in my modpack, but like I said it could be them naturally spawning in the dungeons (they're fairly spacious so mobs can naturally spawn)....probably what it is.
